highlighter: pygments
source: ./
title: mktmpio Docs
baseurl: http://docs.mktmp.io
gems:
  - jekyll-sitemap
lsi: false
defaults:
  - values:
      layout: default
markdown: redcarpet
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
